### ISSUE TITLE
Backend 개인 역할

### ISSUE THREAD

**Issue by JJHeon** [ohouse-clone/ohouse_back#5]
백엔드
API
- 스토어 상품페이지
- 스토어 구매페이지
- 판매자 등록
- 구매 API

개발 환경 구축 및 관리
- ERD 수정 및 관리
- AWS EC2 운영
- AWS RDS 운영
- Github 권한 매니지먼트

PM
- 원활한 개발을 위해 스크럼 및 미팅 진행

**Comment by bjs07** [comment]
- User 기능 추가 및 API 테스트
-게시판 CRUD 개발
-회원가입, 로그인
-집들이 스크랩/하트/필터/댓글 기능 구현
- 배포 및 검토
