### ISSUE TITLE
22.12.15 Scrum Meeting

### ISSUE THREAD

**Issue by mingnana** [ohouse-clone/ohouse_back#72]
23:00 Scrum meeting

- [x] 정헌님
- [ ] 지수님
- [x] 민아님
- [x] 승영님

1. 하셨던 일
2. 하실 일
3. 닥친 문제
4. 필요하신 도움
5. 말하고 싶으신 것

순서로 말해주세요

**Comment by mingnana** [comment]
1. 등록페이지 파일첨부
2. 등록 버튼 클릭시 첨부파일 넘긴후 리스트화시키기
3. x
4. x
5. x

**Comment by syp95** [comment]
1. store 메인페이지 리팩토링 진행중
2. get 요청 처리 api와 연동, 
카테고리 페이지 / 프로덕트 디테일 페이지 완성 ,
판매자 / 프로덕트 결제 페이지 구현
3. x
4. x
5. x

**Comment by JJHeon** [comment]
1. 결제 API 검토, 토스페이먼츠로 결정
2. 토스페이먼츠 API 테스트 및 결제 API 구현 예정
3. X
4. X
5. 개발 기간도 길어지고 연말이 되면서 다들 힘드실거라고 생각합니다. 조금만 더 힘내서 좋은 기억으로 마무리됬으면 좋겠습니다
