### ISSUE TITLE
Issue Label 결정

### ISSUE THREAD

**Issue by JJHeon** [ohouse-clone/ohouse_back#8]
각 번호마다 모두 답을 해주시면 됩니다.

---

### 1번
issue에 등록될 Label을 수정했습니다
무분별하게 늘어나지 않도록 정하고 가려고 합니다.
    - 필요한 것
    - 필요 없다고 생각되는 것
    - 만족
    - label에 대해 궁굼한 점 
의견주세요.

**Label List**
    - bug
    - design
    - discussion : 지금 issue와 같이 논의할 때, 사용 예정
    - duplicate
    - feature
    - help wanted
    - improving
    - invalid
    - question
    - setup
    - test
    
---
### 2번
**기타**
github에 discussion이란 기능이 있는데요. 게시판 기능입니다. 
저는 다음 이유 떄문에 이 기능을 사용하진 않으려고 합니다. 
1. 논의사항과 이슈과 한눈에 다른 이슈와 함께 보이면 좋겠다.
2. 4명의 소규모 인원으로 게시판 기능을 쓰는 것은 과한 것 같다.

그런데 만약 discussion 기능을 사용하고 싶으신분이 있을 수 있어서 여쭤봅니다. 의견 주세요

---

### 3번
앞으로 의견논의를 모두 issue로 관리하려고 합니다. 
scrum과 Document에 해당할 내용은 PRS로 issue를 작성하고
그외 개발 관련된 내용, 토의, 이슈는 ohouse develop Projects로 사용할 예정입니다.

issue와 PR은 함께 관리되며 issue에 따른 feature branch를 만들어서 PR을 만들고자 합니다
그래서 PR이 Merge되면 issue도 close됩니다.

참고 : https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

다른 생각 혹은 더 좋은 아이디어 있으시면 의견 주세요.

**Comment by syp95** [comment]
1. 만족합니다
2. 사용 안하는 편이 좋다 생각합니다! ,논의는 라이브하게 한 후 정리본이 이슈에 올라오는 게 나은 것 같습니다!
3. 좀 더 알아보고 의견 드리겠습니다! (8/26까지 수정하겠습니다)

**Comment by mingnana** [comment]
동의합니다! 생각나는게 있으면 코멘트달아놓도록 하겠습니다. 고생하셨습니다 :)

**Comment by bjs07** [comment]
1. 라벨은 적당한 것 같아요, 써보면서 차차 조정해 나가면 될 듯 합니다.
2. 저도 게시판은 굳이 안 써도 될 것 같아요
3. 괜찮은 것 같아요!

**Comment by JJHeon** [comment]
### Conclusion

1. 아래의 태그들을 사용하겠습니다
- bug
- design
- discussion
- duplicate
- feature
- help wanted
- improving
- invalid
- question
- setup
- test
- fixed (추가됨)
2. 사용안함
3. Issue - PR 사용
